# frozen_string_literal: true

source 'https://rubygems.org'

gem 'jekyll', '4.3.4'
# Ruby 3.4 no longer ships csv as a default gem; Jekyll 4.3.4 still requires it.
gem 'csv'

gem 'jekyll-theme-profile', path: '../../../theme'
